### ISSUE TITLE
HTTP API

### ISSUE THREAD

**Issue by victorb** [LottieFiles/feature-requests#1]
Hello folks!

Seems the pages over at https://lottiefiles.com/recent are rendered server-side, so don't know if you have any backend HTTP API to expose, but would be nice to be able to have access to all the files that have been submitted. Would allow people to build custom frontends and integrate LottieFiles into their development/design tools easier.

**Comment by ahmedmaazin** [comment]
Hey @victorb ,

We're currently rolling out request / invite basis access for our public graphql api. Right now the ability for searching and viewing an animation is there. We're in the works for adding other endpoints such as recent, popular and etc. 

Do send us a request via https://lottiefiles.com/developers. 

Enjoy the integration. Cheers.

**Comment by victorb** [comment]
Ah, that's cool. Sent an invite!

I tried browsing around on lottiefiles.com to find any information, you might want to put what you wrote above on the website somewhere, or make it more obvious where is, if it's already there :)

**Comment by ahmedmaazin** [comment]
Awesome. Thanks @victorb
